# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, Push (Nuget)

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Packages
      working-directory: Dotented
      run: dotnet restore
    - name: Build dotnet core app
      working-directory: Dotented
      run: dotnet build --configuration Release --no-restore
    - name: Run dotnet publish
      working-directory: Dotented
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGETAPIKEY }} --skip-duplicate
